on:
  push:
    branches:
      - master
  pull_request:

concurrency:
  group: ci-${{ github.ref }}
  cancel-in-progress: true

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - run: rustup component add clippy
      - uses: actions-rs/clippy-check@v1
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          args: --all-features

  build:
    needs: lint
    strategy:
      fail-fast: false
      matrix:
        job:
          - { target: x86_64-apple-darwin, exe: macos, os: macos-latest }
    runs-on: ${{ matrix.job.os }}
    steps:
      - uses: actions/checkout@v3
      - uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: 1.64.0
          override: true
          target: ${{ matrix.job.target }}
          components: rust-src
      - uses: actions-rs/cargo@v1
        with:
          use-cross: true
          args: --release --target=${{ matrix.job.target }} --locked
          command: build
      - name: Rename result
        run: |
          rm target/${{ matrix.job.target }}/release/propr.d
          cp target/${{ matrix.job.target }}/release/propr* propr-${{ matrix.job.exe }}
      - name: Archive production artifacts
        uses: actions/upload-artifact@v3
        with:
          name: bin
          path: propr-${{ matrix.job.exe }}

  release:
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/master'
    steps:
      - uses: actions/checkout@v3
      - uses: actions/download-artifact@v3
        with:
          name: bin
          path: bin
      - name: Get current package version
        id: current_version
        run: echo "version=$(make version)" >> $GITHUB_OUTPUT
      - uses: "marvinpinto/action-automatic-releases@latest"
        with:
          repo_token: "${{ secrets.GITHUB_TOKEN }}"
          automatic_release_tag: "${{ steps.current_version.outputs.version }}"
          prerelease: false
          files: |
            ./bin/propr-macos
